"use client";

import { useMemo } from "react";
import Link from "next/link";
import {
  Bar,
  BarChart,
  CartesianGrid,
  Cell,
  Pie,
  PieChart,
  ResponsiveContainer,
  Tooltip as RechartsTooltip,
  XAxis,
  YAxis,
} from "recharts";
import { useProjectStore } from "@/context/project-store-context";
import { useTaxonomyStore } from "@/context/taxonomy-store-context";
import { useDealRoomStore } from "@/context/deal-room-store-context";
import { useUserRoleCounts } from "@/lib/hooks/use-user-role-counts";
import { useInquiryStatusCounts } from "@/lib/hooks/use-inquiry-status-counts";
import { useMouSummary } from "@/lib/hooks/use-mou-summary";
import { useDocumentDownloadCount } from "@/lib/hooks/use-document-download-count";
import { useAuth } from "@/context/auth-context";
import type { AccountRole } from "@/lib/auth/types";
import type { InvestorEngagementStatus, ProjectStatus } from "@/lib/types";
import { parseCapitalTotalMillions, formatMillions } from "@/lib/utils/capital";
import { bucketProvinceLabel } from "@/lib/utils/province";
import {
  ReportShell,
  ReportSection,
  ReportStat,
  ReportTable,
  ReportEmptyState,
  ReportChartFrame,
  ReportChartLegend,
  ReportDataToggle,
  type ReportStatTone,
} from "@/components/reports/report-shell";
import { ROLE_LABELS } from "@/components/dashboard/role-change-modal";

const PROJECT_STATUS_LABELS: Record<ProjectStatus, string> = {
  draft: "Draft",
  submitted_for_review: "Submitted for Review",
  under_review: "Under Review",
  changes_requested: "Changes Requested",
  approved: "Approved",
  published: "Published",
  archived: "Archived",
};

const ENGAGEMENT_STATUS_LABELS: Record<InvestorEngagementStatus, string> = {
  draft: "Draft",
  submitted: "Submitted",
  under_review: "Under Review",
  approved: "Approved",
  rejected: "Rejected",
};

// Light/print theme — deliberately the sovereign zim-* tokens (see globals.css @theme), never the
// dark dashboard palette used elsewhere on the platform, since this report renders on a white page.
const STATUS_COLORS: Partial<Record<ProjectStatus, string>> = {
  draft: "#9ca3af",
  submitted_for_review: "#60a5fa",
  under_review: "#fbbf24",
  changes_requested: "#f97316",
  approved: "#34d399",
  published: "#006400",
  archived: "#6b7280",
};
const ROLE_PIE_COLORS = ["#006400", "#ffd300", "#0ea5e9", "#dc2626", "#6b7280", "#a855f7"];

// This report is only ever generated by Platform Admin / Console Admin, then handed to a minister
// or DFI as a printed/exported brief — so its one "who's on the platform" section should read as
// business participant categories, never raw IT account roles. Internal platform-operator roles
// (admin, super_admin) are deliberately excluded here: they're not market participants.
const INSTITUTIONAL_ROLE_LABELS: Partial<Record<AccountRole, string>> = {
  qualified: "Qualified Institutional Investors",
  government: "Government & Ministry Leads",
  registered: "Prospect / Unverified Inquiries",
};
const INSTITUTIONAL_ROLE_ORDER: AccountRole[] = ["qualified", "government", "registered"];

// Threshold constants for the report's red/amber/green threat-level signaling — deliberately
// applied to only the handful of genuinely alarm-worthy metrics (capital coverage, review
// turnaround, conversion rate) so the signal stays meaningful rather than diluted across every
// tile. Tunable here without touching the render logic below.
const CAPITAL_COVERAGE_WARNING_MAX = 20; // % — below this, capital coverage is a red/amber flag
const REVIEW_DAYS_WARNING_MIN = 15; // days — platform/ministry review turnaround bands
const REVIEW_DAYS_CRITICAL_MIN = 30;
const CONVERSION_RATE_WARNING_MIN = 10; // % — engagement funnel conversion rate

const TONE_HEX: Record<Exclude<ReportStatTone, "neutral">, string> = {
  critical: "#dc2626",
  warning: "#f59e0b",
  good: "#059669",
};

function toneHex(tone: ReportStatTone): string {
  return tone === "neutral" ? "#6b7280" : TONE_HEX[tone];
}

function pctLabel(value: number | null, decimals = 1): string {
  return value === null ? "—" : `${value.toFixed(decimals)}%`;
}

function capitalCoverageTone(pct: number | null): ReportStatTone {
  if (pct === null || pct <= 0) return "critical";
  return pct < CAPITAL_COVERAGE_WARNING_MAX ? "warning" : "good";
}

function reviewDaysTone(days: number | null): ReportStatTone {
  if (days === null) return "neutral";
  if (days > REVIEW_DAYS_CRITICAL_MIN) return "critical";
  return days >= REVIEW_DAYS_WARNING_MIN ? "warning" : "good";
}

function conversionTone(pct: number | null): ReportStatTone {
  if (pct === null) return "neutral";
  return pct < CONVERSION_RATE_WARNING_MIN ? "warning" : "good";
}

/**
 * Comprehensive, high-level report for the government — surfaced via /admin/reports,
 * /super-admin/reports, and the "National Executive Briefing" tab on /deal-room/reports (Platform
 * Admin, Console Admin, and Government respectively), distinguished from the personal Activity
 * Report every other persona gets (see PersonalActivityReport). Government's read access is
 * intentionally narrower than staff's on two data sources — aggregate role/status *counts* only
 * (GET /api/users/role-counts, GET /api/inquiries/status-counts) rather than the full PII-bearing
 * user/inquiry lists — so the numbers on this report are always real, never silently zeroed out
 * by a 403. Intentionally window.print()-based rather than a new PDF pipeline dependency.
 *
 * Government Executive Report Overhaul: fixed a report-side parsing bug that concatenated/mis-
 * scaled free-text capital figures into nonsensical totals (e.g. "$112.8T") — capital aggregation
 * now reuses the same `parseCapitalTotalMillions`/`formatMillions` parser already used correctly
 * on 7+ other pages (see lib/utils/capital.ts, lib/data/site-stats.ts). Also adds strategic
 * metrics (capital coverage, review turnaround, provincial distribution, employment impact) and
 * chart visuals — all derived from existing data, plus the two additions explicitly approved:
 * jobsDirect/jobsIndirect columns and the MOU summary endpoint.
 */
export function GovernmentExecutiveReport() {
  const { name, role } = useAuth();
  // Report is only ever rendered from /super-admin/reports or /admin/reports, so the drill-down
  // links below must point back into whichever console the current viewer actually has.
  const usersBasePath = role === "super_admin" ? "/super-admin/users" : "/admin/users";
  const { projects, isLoading: projectsLoading } = useProjectStore();
  const { sectors, ministries, isLoading: taxonomyLoading } = useTaxonomyStore();
  const { engagements, isLoading: engagementsLoading } = useDealRoomStore();
  const { counts: roleCounts, total: userTotal, isLoading: usersLoading } = useUserRoleCounts();
  const { counts: inquiryStatusCounts, total: inquiryTotal, isLoading: inquiriesLoading } = useInquiryStatusCounts();
  const { counts: mouCounts, isLoading: mouLoading } = useMouSummary();
  const { count: documentDownloadCount, isLoading: downloadCountLoading } = useDocumentDownloadCount();

  const isLoading =
    projectsLoading ||
    taxonomyLoading ||
    inquiriesLoading ||
    engagementsLoading ||
    usersLoading ||
    mouLoading ||
    downloadCountLoading;

  // --- Capital (the actual bug fix) -----------------------------------------------------------
  // Each project's headline capital figure, correctly scaled ("million"/"billion" honored, never
  // concatenating multiple distinct dollar figures) — `null` means unparseable/"assessment
  // pending", excluded from sums rather than silently coerced to a garbage number.
  const capitalByProject = useMemo(
    () => projects.map((p) => ({ project: p, millions: parseCapitalTotalMillions(p.capitalRequired) })),
    [projects]
  );
  const unassessedCount = useMemo(() => capitalByProject.filter((c) => c.millions === null).length, [capitalByProject]);
  const totalCapitalMillions = useMemo(
    () => capitalByProject.reduce((sum, c) => sum + (c.millions ?? 0), 0),
    [capitalByProject]
  );
  const publishedCapitalMillions = useMemo(
    () =>
      capitalByProject
        .filter((c) => c.project.projectStatus === "published")
        .reduce((sum, c) => sum + (c.millions ?? 0), 0),
    [capitalByProject]
  );

  // --- Average Project Capital Size + Publication Rate (Layer 3 replacements for GFCF%/drawdown
  // schedule — both dropped entirely since neither is derivable without external data or
  // fabrication; these two are 100% real, derived purely from existing project records) ---------
  const assessedProjectCount = projects.length - unassessedCount;
  const avgCapitalMillions = assessedProjectCount > 0 ? totalCapitalMillions / assessedProjectCount : null;
  const publishedCount = useMemo(() => projects.filter((p) => p.projectStatus === "published").length, [projects]);
  const publicationRate = projects.length > 0 ? (publishedCount / projects.length) * 100 : null;

  const statusRows = useMemo(() => {
    const counts: Partial<Record<ProjectStatus, number>> = {};
    for (const p of projects) counts[p.projectStatus] = (counts[p.projectStatus] ?? 0) + 1;
    return (Object.keys(PROJECT_STATUS_LABELS) as ProjectStatus[])
      .filter((s) => counts[s])
      .map((s) => [PROJECT_STATUS_LABELS[s], counts[s] ?? 0]);
  }, [projects]);

  // Sorted by capital concentration (not raw count) — the point of this section is showing where
  // the money is, per the "instantly displays capital concentration" chart brief.
  const sectorChartData = useMemo(() => {
    return sectors
      .map((s) => {
        const sectorProjects = projects.filter((p) => p.sectorId === s.id);
        const capitalMillions = sectorProjects.reduce(
          (sum, p) => sum + (parseCapitalTotalMillions(p.capitalRequired) ?? 0),
          0
        );
        return { name: s.shortName ?? s.name, count: sectorProjects.length, capitalMillions };
      })
      .filter((s) => s.count > 0)
      .sort((a, b) => b.capitalMillions - a.capitalMillions);
  }, [sectors, projects]);
  const sectorRows = useMemo(
    () => sectorChartData.map((s) => [s.name, s.count, formatMillions(s.capitalMillions)]),
    [sectorChartData]
  );

  const ministryRows = useMemo(() => {
    return ministries
      .map((m) => ({ name: m.shortName ?? m.name, count: projects.filter((p) => p.primaryBeneficiaryMinistryId === m.id).length }))
      .filter((m) => m.count > 0)
      .sort((a, b) => b.count - a.count)
      .map((m) => [m.name, m.count]);
  }, [ministries, projects]);

  // Top 8 ministries by project volume, status-stacked — keeps the chart legible; the full list
  // stays available in the Pipeline by Beneficiary Ministry table above.
  const ministryStatusChartData = useMemo(() => {
    return ministries
      .map((m) => {
        const ministryProjects = projects.filter((p) => p.primaryBeneficiaryMinistryId === m.id);
        if (ministryProjects.length === 0) return null;
        const counts: Partial<Record<ProjectStatus, number>> = {};
        for (const p of ministryProjects) counts[p.projectStatus] = (counts[p.projectStatus] ?? 0) + 1;
        return { name: m.shortName ?? m.name, total: ministryProjects.length, ...counts };
      })
      .filter((m): m is NonNullable<typeof m> => m !== null)
      .sort((a, b) => b.total - a.total)
      .slice(0, 8);
  }, [ministries, projects]);

  // Only legend the statuses actually present in the Top-8 chart above, not every possible status.
  const ministryStatusLegend = useMemo(
    () =>
      (Object.keys(PROJECT_STATUS_LABELS) as ProjectStatus[])
        .filter((status) => ministryStatusChartData.some((m) => (m[status] ?? 0) > 0))
        .map((status) => ({ label: PROJECT_STATUS_LABELS[status], color: STATUS_COLORS[status] ?? "#9ca3af" })),
    [ministryStatusChartData]
  );

  const engagementRows = useMemo(() => {
    const counts: Partial<Record<InvestorEngagementStatus, number>> = {};
    for (const e of engagements) counts[e.status] = (counts[e.status] ?? 0) + 1;
    return (Object.keys(ENGAGEMENT_STATUS_LABELS) as InvestorEngagementStatus[])
      .filter((s) => counts[s])
      .map((s) => [ENGAGEMENT_STATUS_LABELS[s], counts[s] ?? 0]);
  }, [engagements]);

  // --- Investor Engagement Funnel (4-stage, incl. MOU Executed) ------------------------------
  // A current-status-distribution snapshot presented in workflow order — NOT a cohort-conversion
  // funnel. Engagements have no stage-entry timestamps today, so true cohort tracking (e.g. "of
  // the engagements submitted in June, X% reached Approved") isn't derivable yet; this is a
  // deliberate, honest simplification rather than an overclaim.
  const funnel = useMemo(() => {
    const submitted = engagements.filter((e) => e.status === "submitted").length;
    const underReview = engagements.filter((e) => e.status === "under_review").length;
    const approved = engagements.filter((e) => e.status === "approved").length;
    const rejected = engagements.filter((e) => e.status === "rejected").length;
    const mouExecuted = mouCounts.executed ?? 0;
    const decidedOrInFlight = submitted + underReview + approved + rejected;
    const conversionRate = decidedOrInFlight > 0 ? (approved / decidedOrInFlight) * 100 : null;
    return {
      chartData: [
        { stage: "Submitted", count: submitted },
        { stage: "Under Review", count: underReview },
        { stage: "Approved", count: approved },
        { stage: "MOU Executed", count: mouExecuted },
      ],
      rejected,
      conversionRate,
    };
  }, [engagements, mouCounts]);

  // --- Investor Capital Coverage --------------------------------------------------------------
  // Indicative ticket sizes on active (non-draft, non-rejected) engagements vs. published-project
  // capital — "how much of the live pipeline already has a soft commitment behind it".
  const capitalCoverage = useMemo(() => {
    const active = engagements.filter((e) => e.status !== "draft" && e.status !== "rejected");
    const ticketMillions = active.reduce((sum, e) => sum + (parseCapitalTotalMillions(e.ticketSize) ?? 0), 0);
    const pct = publishedCapitalMillions > 0 ? (ticketMillions / publishedCapitalMillions) * 100 : null;
    return { ticketMillions, pct, engagementCount: active.length };
  }, [engagements, publishedCapitalMillions]);

  // --- Average Days in Review (platform + per-ministry) ---------------------------------------
  const reviewTurnaround = useMemo(() => {
    const items = projects
      .filter((p) => p.submittedAt && p.approvedAt)
      .map((p) => ({
        ministryId: p.primaryBeneficiaryMinistryId,
        days: (new Date(p.approvedAt as string).getTime() - new Date(p.submittedAt as string).getTime()) / 86_400_000,
      }));
    const platformAvg = items.length > 0 ? items.reduce((sum, i) => sum + i.days, 0) / items.length : null;

    const byMinistry = new Map<string, number[]>();
    for (const item of items) {
      const bucket = byMinistry.get(item.ministryId) ?? [];
      bucket.push(item.days);
      byMinistry.set(item.ministryId, bucket);
    }
    const chartItems = ministries
      .map((m) => {
        const days = byMinistry.get(m.id);
        if (!days || days.length === 0) return null;
        const avg = days.reduce((sum, d) => sum + d, 0) / days.length;
        return { name: m.shortName ?? m.name, avg, sampleSize: days.length };
      })
      .filter((r): r is NonNullable<typeof r> => r !== null)
      .sort((a, b) => a.avg - b.avg);

    const rows = chartItems.map((r) => [r.name, `${r.avg.toFixed(1)} days`, r.sampleSize]);
    const hasNearZeroEntry = chartItems.some((r) => r.avg < 0.5);

    return { platformAvg, chartItems, rows, sampleSize: items.length, hasNearZeroEntry };
  }, [projects, ministries]);

  // --- Provincial Pipeline Distribution --------------------------------------------------------
  // Published projects only, same "only a live investable opportunity backs a displayable
  // estimate" rule already used in lib/data/site-stats.ts. `province` is free text pending a
  // canonical FK (see BACKLOG.md) — `bucketProvinceLabel` cleans deck-validation notes out of the
  // display label and folds any multi-province string (e.g. "Midlands / Manicaland") into one
  // "Multi-Province / National" bucket, rather than one illegible bar per unique combination.
  // Capped to Top 5 single provinces + Multi-Province/National + Unspecified + a rolled-up
  // "Other" tail, so the chart stays legible regardless of how many distinct provinces appear.
  const provincialData = useMemo(() => {
    const map = new Map<string, { count: number; capitalMillions: number }>();
    for (const p of projects.filter((p) => p.projectStatus === "published")) {
      const key = bucketProvinceLabel(p.province?.trim() || "");
      const entry = map.get(key) ?? { count: 0, capitalMillions: 0 };
      entry.count += 1;
      entry.capitalMillions += parseCapitalTotalMillions(p.capitalRequired) ?? 0;
      map.set(key, entry);
    }
    const all = Array.from(map.entries()).map(([name, v]) => ({ name, ...v }));
    const pinned = all.filter((r) => r.name === "Multi-Province / National" || r.name === "Unspecified");
    const singleProvinces = all
      .filter((r) => r.name !== "Multi-Province / National" && r.name !== "Unspecified")
      .sort((a, b) => b.capitalMillions - a.capitalMillions);

    const top5 = singleProvinces.slice(0, 5);
    const tail = singleProvinces.slice(5);
    const other =
      tail.length > 0
        ? [
            {
              name: `Other (${tail.reduce((sum, r) => sum + r.count, 0)})`,
              count: tail.reduce((sum, r) => sum + r.count, 0),
              capitalMillions: tail.reduce((sum, r) => sum + r.capitalMillions, 0),
            },
          ]
        : [];

    return [...top5, ...pinned, ...other].sort((a, b) => b.capitalMillions - a.capitalMillions);
  }, [projects]);

  // --- Employment Impact (hide entirely if nothing has been entered yet) ----------------------
  const jobsImpact = useMemo(() => {
    const published = projects.filter((p) => p.projectStatus === "published");
    const direct = published.reduce((sum, p) => sum + (p.jobsDirect ?? 0), 0);
    const indirect = published.reduce((sum, p) => sum + (p.jobsIndirect ?? 0), 0);
    return { direct, indirect, total: direct + indirect };
  }, [projects]);

  const institutionalParticipants = useMemo(() => {
    return INSTITUTIONAL_ROLE_ORDER.filter((r) => (roleCounts[r] ?? 0) > 0).map((r) => ({
      role: r,
      name: INSTITUTIONAL_ROLE_LABELS[r]!,
      value: roleCounts[r] ?? 0,
    }));
  }, [roleCounts]);
  const participantLegend = useMemo(
    () => institutionalParticipants.map((p, i) => ({ label: p.name, color: ROLE_PIE_COLORS[i % ROLE_PIE_COLORS.length] })),
    [institutionalParticipants]
  );

  const inquiryRows = useMemo(
    () => Object.entries(inquiryStatusCounts).map(([s, n]) => [s.charAt(0).toUpperCase() + s.slice(1), n]),
    [inquiryStatusCounts]
  );

  // Totals used purely for the "% of total" tooltip enrichment on the Sector/Provincial charts.
  const sectorCapitalTotal = useMemo(() => sectorChartData.reduce((sum, s) => sum + s.capitalMillions, 0), [sectorChartData]);
  const provincialCapitalTotal = useMemo(() => provincialData.reduce((sum, p) => sum + p.capitalMillions, 0), [provincialData]);

  function capitalTooltipFormatter(total: number) {
    return (value: unknown) => {
      const v = Number(value);
      const pct = total > 0 ? ((v / total) * 100).toFixed(1) : "0.0";
      return `${formatMillions(v)} · ${pct}% of total`;
    };
  }

  return (
    <ReportShell
      title="Government Executive Report"
      subtitle="Comprehensive, platform-wide overview of the national investment pipeline"
      generatedBy={`${name ?? "—"} (${role ? ROLE_LABELS[role] : "—"})`}
      generatedAt={new Date().toLocaleString()}
      classification="For Government Use"
    >
      {isLoading ? (
        <p className="text-sm text-zim-muted">Loading report data…</p>
      ) : (
        <>
          {/* Layer 1 — Executive Command Strip: the handful of metrics a Cabinet-level reader
              needs in the first 30 seconds, red/amber/green toned where a genuine alarm exists. */}
          <ReportSection title="Executive Command Strip">
            <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
              <ReportStat label="Total Pipeline Value" value={formatMillions(totalCapitalMillions)} hint={`${projects.length} project(s) tracked`} />
              <ReportStat
                label="Investor Capital Coverage"
                value={pctLabel(capitalCoverage.pct)}
                tone={capitalCoverageTone(capitalCoverage.pct)}
                hint={
                  capitalCoverage.engagementCount > 0
                    ? `${formatMillions(capitalCoverage.ticketMillions)} committed of ${formatMillions(publishedCapitalMillions)} published`
                    : "No active engagement ticket sizes logged yet"
                }
                actionHint="Action needed: activate Relationship Desk outreach"
              />
              <ReportStat
                label="Avg. Review Turnaround"
                value={reviewTurnaround.platformAvg !== null ? `${reviewTurnaround.platformAvg.toFixed(1)} days` : "—"}
                tone={reviewDaysTone(reviewTurnaround.platformAvg)}
                hint={reviewTurnaround.sampleSize > 0 ? `${reviewTurnaround.sampleSize} project(s) submitted → approved` : "No completed reviews yet"}
                actionHint="Action needed: review ministry clearance queue"
              />
              <ReportStat
                label="Funnel Conversion Rate"
                value={pctLabel(funnel.conversionRate)}
                tone={conversionTone(funnel.conversionRate)}
                hint={`${funnel.chartData[3].count} MOU(s) executed of ${engagements.length} engagement(s)`}
              />
            </div>
            <div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-5">
              <ReportStat label="Total Projects" value={projects.length} />
              <ReportStat label="Published" value={publishedCount} />
              <ReportStat label="Total Investor Engagements" value={engagements.length} />
              <ReportStat label="Registered Platform Users" value={userTotal} />
              <ReportStat label="Lead Inquiries Received" value={inquiryTotal} />
            </div>
          </ReportSection>

          {/* Layer 3 — Economic & Platform Impact: only ever real, database-derived numbers.
              Employment Impact is the headline sovereign metric; Avg. Capital Size and
              Publication Rate replace the dropped GFCF%/drawdown-schedule mockup items; Document
              Downloads is real background telemetry (see the download route's audit-log write)
              and stays hidden entirely until a genuine download happens. */}
          <ReportSection title="Economic & Platform Impact">
            <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
              {jobsImpact.total > 0 && (
                <>
                  <ReportStat label="Direct Jobs Projected" value={jobsImpact.direct.toLocaleString()} />
                  <ReportStat label="Indirect Jobs Projected" value={jobsImpact.indirect.toLocaleString()} />
                  <ReportStat label="Total Employment Impact" value={jobsImpact.total.toLocaleString()} hint="Published projects only" />
                </>
              )}
              <ReportStat
                label="Avg. Project Capital Size"
                value={avgCapitalMillions !== null ? formatMillions(avgCapitalMillions) : "—"}
                hint={`${assessedProjectCount} assessed project(s)`}
              />
              <ReportStat
                label="Publication Rate"
                value={pctLabel(publicationRate)}
                hint={`${publishedCount} of ${projects.length} project(s) published`}
              />
              {documentDownloadCount > 0 && (
                <ReportStat
                  label="Document Downloads"
                  value={documentDownloadCount.toLocaleString()}
                  hint="Tracked since this release — real investor/staff activity only"
                />
              )}
            </div>
          </ReportSection>

          <ReportSection title="Pipeline by Status">
            <ReportTable columns={["Status", "Projects"]} rows={statusRows} />
          </ReportSection>

          {/* Layer 2 — Consolidated Visual Analytics Grid: charts paired side-by-side at a common
              height, each with a screen-collapsible (always print-visible) data table beneath it
              instead of a permanently duplicated table. */}
          <div className="mb-6 grid grid-cols-1 gap-6 lg:grid-cols-2">
            <ReportSection title="Capital Required by Sector" breakBefore>
              {sectorChartData.length > 0 ? (
                <>
                  <ReportChartFrame height={260}>
                    <ResponsiveContainer>
                      <BarChart data={sectorChartData} layout="vertical" margin={{ left: 24, right: 24 }}>
                        <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" horizontal={false} />
                        <XAxis type="number" tick={{ fill: "#6b7280", fontSize: 11 }} tickFormatter={(v) => formatMillions(v)} />
                        <YAxis type="category" dataKey="name" tick={{ fill: "#2b2b2b", fontSize: 11 }} width={100} />
                        <RechartsTooltip
                          cursor={{ fill: "rgba(0,100,0,0.06)" }}
                          contentStyle={{ backgroundColor: "#fff", border: "1px solid #e5e7eb" }}
                          formatter={capitalTooltipFormatter(sectorCapitalTotal)}
                        />
                        <Bar dataKey="capitalMillions" name="Capital" fill="#006400" radius={[0, 4, 4, 0]} />
                      </BarChart>
                    </ResponsiveContainer>
                  </ReportChartFrame>
                  <ReportDataToggle>
                    <ReportTable columns={["Sector", "Projects", "Capital Required"]} rows={sectorRows} />
                  </ReportDataToggle>
                </>
              ) : (
                <ReportEmptyState message="No sector-tagged projects for this snapshot." />
              )}
            </ReportSection>

            <ReportSection title="Provincial Pipeline Distribution">
              {provincialData.length > 0 ? (
                <>
                  <ReportChartFrame height={260}>
                    <ResponsiveContainer>
                      <BarChart data={provincialData} layout="vertical" margin={{ left: 24, right: 24 }}>
                        <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" horizontal={false} />
                        <XAxis type="number" tick={{ fill: "#6b7280", fontSize: 11 }} tickFormatter={(v) => formatMillions(v)} />
                        <YAxis type="category" dataKey="name" tick={{ fill: "#2b2b2b", fontSize: 11 }} width={100} />
                        <RechartsTooltip
                          cursor={{ fill: "rgba(255,211,0,0.15)" }}
                          contentStyle={{ backgroundColor: "#fff", border: "1px solid #e5e7eb" }}
                          formatter={capitalTooltipFormatter(provincialCapitalTotal)}
                        />
                        <Bar dataKey="capitalMillions" name="Capital" fill="#ffd300" radius={[0, 4, 4, 0]} />
                      </BarChart>
                    </ResponsiveContainer>
                  </ReportChartFrame>
                  <ReportDataToggle>
                    <ReportTable
                      columns={["Province", "Published Projects", "Capital"]}
                      rows={provincialData.map((p) => [p.name, p.count, formatMillions(p.capitalMillions)])}
                    />
                  </ReportDataToggle>
                </>
              ) : (
                <ReportEmptyState message="No published projects with a recorded province for this snapshot." />
              )}
            </ReportSection>

            <ReportSection title="Ministry Review-Turnaround Bottleneck">
              {reviewTurnaround.chartItems.length > 0 ? (
                <>
                  <ReportChartFrame height={260}>
                    <ResponsiveContainer>
                      <BarChart data={reviewTurnaround.chartItems} layout="vertical" margin={{ left: 24, right: 24 }}>
                        <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" horizontal={false} />
                        <XAxis type="number" tick={{ fill: "#6b7280", fontSize: 11 }} tickFormatter={(v) => `${v}d`} />
                        <YAxis type="category" dataKey="name" tick={{ fill: "#2b2b2b", fontSize: 11 }} width={100} />
                        <RechartsTooltip
                          cursor={{ fill: "rgba(0,100,0,0.06)" }}
                          contentStyle={{ backgroundColor: "#fff", border: "1px solid #e5e7eb" }}
                          formatter={(value) => `${Number(value).toFixed(1)} days`}
                        />
                        <Bar dataKey="avg" name="Avg. Turnaround (days)" radius={[0, 4, 4, 0]}>
                          {reviewTurnaround.chartItems.map((item) => (
                            <Cell key={item.name} fill={toneHex(reviewDaysTone(item.avg))} />
                          ))}
                        </Bar>
                      </BarChart>
                    </ResponsiveContainer>
                  </ReportChartFrame>
                  <ReportDataToggle>
                    <ReportTable columns={["Ministry", "Avg. Turnaround", "Projects Sampled"]} rows={reviewTurnaround.rows} />
                  </ReportDataToggle>
                </>
              ) : (
                <ReportEmptyState message="No completed ministry reviews (submitted → approved) for this snapshot." />
              )}
            </ReportSection>

            <ReportSection title="Investor Engagement Funnel">
              <ReportChartFrame height={260}>
                <ResponsiveContainer>
                  <BarChart data={funnel.chartData} margin={{ left: -10 }}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" vertical={false} />
                    <XAxis dataKey="stage" tick={{ fill: "#2b2b2b", fontSize: 11 }} />
                    <YAxis tick={{ fill: "#6b7280", fontSize: 11 }} allowDecimals={false} />
                    <RechartsTooltip cursor={{ fill: "rgba(0,100,0,0.06)" }} contentStyle={{ backgroundColor: "#fff", border: "1px solid #e5e7eb" }} />
                    <Bar dataKey="count" name="Engagements" fill="#006400" radius={[4, 4, 0, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              </ReportChartFrame>
              <div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3">
                <ReportStat
                  label="Conversion Rate"
                  value={pctLabel(funnel.conversionRate)}
                  tone={conversionTone(funnel.conversionRate)}
                  hint="Approved ÷ (Submitted + Under Review + Approved + Rejected)"
                />
                <ReportStat label="Rejected" value={funnel.rejected} />
                <ReportStat label="MOU Executed" value={funnel.chartData[3].count} />
              </div>
              <ReportDataToggle>
                <ReportTable columns={["Stage", "Engagements"]} rows={engagementRows} />
              </ReportDataToggle>
            </ReportSection>
          </div>

          {ministryRows.length > 0 && (
            <ReportSection title="Pipeline by Beneficiary Ministry">
              <ReportTable columns={["Ministry", "Projects"]} rows={ministryRows} />
              {ministryStatusChartData.length > 0 && (
                <div className="mt-3">
                  <ReportChartFrame height={260}>
                    <ResponsiveContainer>
                      <BarChart data={ministryStatusChartData} margin={{ left: -10, bottom: 40 }}>
                        <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" vertical={false} />
                        <XAxis
                          dataKey="name"
                          tick={{ fill: "#2b2b2b", fontSize: 10 }}
                          angle={-30}
                          textAnchor="end"
                          interval={0}
                          height={60}
                        />
                        <YAxis tick={{ fill: "#6b7280", fontSize: 11 }} allowDecimals={false} />
                        <RechartsTooltip cursor={{ fill: "rgba(0,100,0,0.06)" }} contentStyle={{ backgroundColor: "#fff", border: "1px solid #e5e7eb" }} />
                        {(Object.keys(PROJECT_STATUS_LABELS) as ProjectStatus[]).map((status) => (
                          <Bar
                            key={status}
                            dataKey={status}
                            name={PROJECT_STATUS_LABELS[status]}
                            stackId="status"
                            fill={STATUS_COLORS[status]}
                          />
                        ))}
                      </BarChart>
                    </ResponsiveContainer>
                  </ReportChartFrame>
                  <ReportChartLegend items={ministryStatusLegend} />
                  <p className="mt-1 text-center text-[11px] text-zim-muted">Top 8 ministries by project volume, status-stacked.</p>
                </div>
              )}
            </ReportSection>
          )}

          <ReportSection title="Institutional Participant Summary">
            <p className="mb-2 text-[11px] text-zim-muted">
              Active market participants evaluating national opportunities — internal platform-operator accounts
              (ZIDA Admin, Platform Admin) are excluded from this business-facing view.
            </p>
            {institutionalParticipants.length > 0 ? (
              <div className="flex flex-col items-center gap-3 sm:flex-row">
                <ReportChartFrame height={180}>
                  <ResponsiveContainer width={180} height={180}>
                    <PieChart>
                      <Pie data={institutionalParticipants} dataKey="value" nameKey="name" innerRadius={40} outerRadius={75} paddingAngle={2}>
                        {institutionalParticipants.map((entry, i) => (
                          <Cell key={entry.role} fill={ROLE_PIE_COLORS[i % ROLE_PIE_COLORS.length]} />
                        ))}
                      </Pie>
                      <RechartsTooltip contentStyle={{ backgroundColor: "#fff", border: "1px solid #e5e7eb" }} />
                    </PieChart>
                  </ResponsiveContainer>
                </ReportChartFrame>
                <div className="flex-1">
                  <table className="w-full border-collapse text-sm">
                    <thead>
                      <tr className="border-b border-zim-border text-left">
                        <th className="py-1.5 pr-4 text-[11px] uppercase tracking-wide text-zim-muted">Category</th>
                        <th className="py-1.5 pr-4 text-[11px] uppercase tracking-wide text-zim-muted">Accounts</th>
                      </tr>
                    </thead>
                    <tbody>
                      {institutionalParticipants.map((p) => (
                        <tr key={p.role} className="border-b border-zim-border/60">
                          <td className="py-1.5 pr-4 text-zim-charcoal print:text-zim-charcoal">
                            <Link
                              href={`${usersBasePath}?role=${p.role}`}
                              className="print:no-underline hover:underline hover:text-zim-green-700"
                              title={`View ${p.name} accounts in Users & Roles`}
                            >
                              {p.name}
                            </Link>
                          </td>
                          <td className="py-1.5 pr-4 text-zim-charcoal">
                            <Link href={`${usersBasePath}?role=${p.role}`} className="print:no-underline hover:underline hover:text-zim-green-700">
                              {p.value}
                            </Link>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                  <p className="mt-1 text-[10px] text-zim-muted print:hidden">Click a category to open the filtered Users &amp; Roles workspace.</p>
                </div>
              </div>
            ) : (
              <ReportEmptyState message="No institutional participants recorded for this snapshot." />
            )}
            <ReportChartLegend items={participantLegend} />
          </ReportSection>

          <ReportSection title="Lead Inquiries by Status">
            <ReportTable columns={["Status", "Inquiries"]} rows={inquiryRows} emptyMessage="No lead inquiries logged during this reporting window." />
          </ReportSection>

          {/* Formal analyst footnotes — consolidated here instead of scattered inline disclaimers,
              so the primary charts/tiles above read as a clean executive document. */}
          <ReportSection title="Methodology & Data Notes" breakBefore>
            <ul className="list-disc space-y-1.5 pl-4 text-xs text-zim-muted">
              <li>
                The Investor Engagement Funnel is a current status-distribution snapshot presented in workflow order,
                not a cohort-conversion funnel — engagement records don&apos;t yet carry stage-entry timestamps.
              </li>
              {reviewTurnaround.hasNearZeroEntry && (
                <li>
                  Ministry review-turnaround entries near 0.0 days reflect same-day/pre-vetted approvals in the
                  underlying record, not a tracking gap.
                </li>
              )}
              {unassessedCount > 0 && (
                <li>{unassessedCount} project(s) are excluded from capital totals — no parseable capital figure has been assessed yet.</li>
              )}
              <li>
                Provincial distribution aggregates any project spanning multiple provinces or national scope into a
                single &quot;Multi-Province / National&quot; bucket, and rolls provinces beyond the top 5 by capital into
                &quot;Other&quot; — every published project is still counted, just grouped for legibility.
              </li>
              <li>Document Downloads reflects real, timestamped download events recorded from this release onward; it is not backfilled.</li>
            </ul>
          </ReportSection>
        </>
      )}
    </ReportShell>
  );
}
