"use client";

import { useEffect, useState } from "react";
import { Printer } from "lucide-react";
import { Button } from "@/components/ui/button";

interface ReportShellProps {
  title: string;
  subtitle: string;
  generatedBy: string;
  generatedAt: string;
  classification?: string;
  children: React.ReactNode;
}

/** Deterministic, non-cryptographic report reference tag (e.g. "REP-20260724-8A9F") derived from
 *  the title + generation timestamp — a human-friendly citation handle for "which printout is
 *  this", NOT a tamper-evidence/verification hash (that would need server-side signing, out of
 *  scope here). Same title+timestamp always renders the same tag. */
function buildReferenceTag(title: string, generatedAt: string): string {
  const date = new Date(generatedAt);
  const datePart = Number.isNaN(date.getTime())
    ? "00000000"
    : `${date.getFullYear()}${String(date.getMonth() + 1).padStart(2, "0")}${String(date.getDate()).padStart(2, "0")}`;
  let hash = 0;
  const seed = `${title}::${generatedAt}`;
  for (let i = 0; i < seed.length; i++) {
    hash = (hash * 31 + seed.charCodeAt(i)) >>> 0;
  }
  const suffix = hash.toString(16).toUpperCase().padStart(4, "0").slice(-4);
  return `REP-${datePart}-${suffix}`;
}

/**
 * Shared printable-report chrome — window.print()-based (no new PDF dependency, per the
 * super-admin "comprehensive report" feedback item). The `report-print` wrapper + globals.css'
 * `@media print` rules hide the dashboard sidebar/topbar and force a clean white letter-format
 * page when the operator prints or "Save as PDF" from the browser dialog.
 */
export function ReportShell({ title, subtitle, generatedBy, generatedAt, classification, children }: ReportShellProps) {
  // `generatedAt` is `new Date().toLocaleString()` computed inline by the caller, so it's a fresh
  // timestamp on every render — it will always differ (even by milliseconds) between the SSR pass
  // and the client's first render, causing a hydration mismatch (amplified further once hashed
  // into `referenceTag`, since a 1ms timestamp difference produces a completely different hash).
  // Fix: render a stable placeholder on both the server and the client's pre-hydration pass, then
  // swap in the real, client-only timestamp/tag after mount — a post-hydration state update is
  // never compared against the SSR HTML, so this can never mismatch.
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);
  const referenceTag = mounted ? buildReferenceTag(title, generatedAt) : "—";
  const snapshotAt = mounted ? generatedAt : "—";

  return (
    <div>
      <div className="mb-4 flex flex-wrap items-center justify-between gap-3 print:hidden">
        <div>
          <h1 className="text-2xl font-semibold text-white">{title}</h1>
          <p className="text-sm mt-1" style={{ color: "var(--color-text-secondary)" }}>
            {subtitle}
          </p>
        </div>
        <Button size="sm" onClick={() => window.print()}>
          <Printer className="h-4 w-4" /> Print / Save as PDF
        </Button>
      </div>

      <div className="report-print rounded-lg bg-white p-8 text-zim-charcoal shadow-xl">
        <div className="mb-6 flex items-start justify-between border-b border-zim-border pb-4">
          <div>
            <p className="text-xs font-semibold uppercase tracking-widest text-zim-green-700">
              Republic of Zimbabwe · Investment Platform
            </p>
            <h2 className="mt-1 text-2xl font-bold text-zim-charcoal">{title}</h2>
            <p className="mt-0.5 text-sm text-zim-muted">{subtitle}</p>
          </div>
          <div className="flex shrink-0 flex-col items-end gap-1.5">
            {classification && (
              <span className="rounded-full border border-amber-300 bg-amber-50 px-3 py-1 text-[11px] font-semibold uppercase tracking-wide text-amber-800">
                {classification}
              </span>
            )}
            <span className="font-mono text-[10px] tracking-wide text-zim-muted">Ref: {referenceTag}</span>
          </div>
        </div>

        <div className="mb-6 grid grid-cols-2 gap-4 text-sm sm:grid-cols-3">
          <div>
            <p className="text-[11px] uppercase tracking-wide text-zim-muted">Generated by</p>
            <p className="mt-0.5 font-medium text-zim-charcoal">{generatedBy}</p>
          </div>
          <div>
            <p className="text-[11px] uppercase tracking-wide text-zim-muted">Snapshot as of</p>
            <p className="mt-0.5 font-medium text-zim-charcoal">{snapshotAt}</p>
          </div>
          <div>
            <p className="text-[11px] uppercase tracking-wide text-zim-muted">Source</p>
            <p className="mt-0.5 font-medium text-zim-charcoal">Live platform data</p>
          </div>
        </div>

        {children}

        <div className="mt-8 border-t border-zim-border pt-4 text-[11px] text-zim-muted">
          Confidential — prepared for internal and government stakeholder use. This is a live snapshot reflecting
          the platform state at the moment of generation (not a bounded reporting period) and is not a substitute
          for audited financial statements.
        </div>
      </div>
    </div>
  );
}

export type ReportStatTone = "critical" | "warning" | "good" | "neutral";

// Left-border accent + value color only (never a filled background) — reads as an instant
// red/amber/green threat signal without burning ink on a printed/PDF page.
const TONE_STYLES: Record<ReportStatTone, { border: string; value: string; badge: string }> = {
  critical: { border: "border-l-4 border-l-red-600", value: "text-red-700", badge: "bg-red-50 text-red-700" },
  warning: { border: "border-l-4 border-l-amber-500", value: "text-amber-700", badge: "bg-amber-50 text-amber-700" },
  good: { border: "border-l-4 border-l-emerald-600", value: "text-emerald-700", badge: "bg-emerald-50 text-emerald-700" },
  neutral: { border: "", value: "text-zim-charcoal", badge: "" },
};

/** A labeled KPI tile used inside report bodies — plain, print-friendly styling (no dark theme).
 *  `tone` drives an instant red/amber/green threat-level signal for the handful of genuinely
 *  alarm-worthy metrics (0% capital coverage, a 45-day review bottleneck, etc.) — deliberately not
 *  applied to every tile, so the signal stays meaningful. `actionHint` renders only for
 *  critical/warning tones, surfacing the "so what should I do about this" line executives expect
 *  next to a flagged metric. */
export function ReportStat({
  label,
  value,
  hint,
  tone = "neutral",
  actionHint,
}: {
  label: string;
  value: string | number;
  hint?: string;
  tone?: ReportStatTone;
  actionHint?: string;
}) {
  const styles = TONE_STYLES[tone];
  // Long string values (an email address, an organization name) at text-xl/bold have nowhere to
  // wrap and will overflow past their grid cell into the neighbor — `min-w-0` lets `truncate`
  // actually engage inside a CSS grid column, and a smaller size keeps long values legible
  // instead of just clipping them; numeric/short KPI values (the common case) are unaffected.
  const isLongText = typeof value === "string" && value.length > 18;
  return (
    <div className={`min-w-0 rounded-md border border-zim-border p-3 ${styles.border}`}>
      <p className="text-[11px] uppercase tracking-wide text-zim-muted">{label}</p>
      <p
        className={`mt-1 truncate font-bold ${styles.value} ${isLongText ? "text-sm" : "text-xl"}`}
        title={typeof value === "string" ? value : undefined}
      >
        {value}
      </p>
      {hint && <p className="mt-0.5 text-xs text-zim-muted">{hint}</p>}
      {actionHint && tone !== "neutral" && (
        <p className={`mt-1.5 inline-block rounded px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-wide ${styles.badge}`}>
          {actionHint}
        </p>
      )}
    </div>
  );
}

/** Clean, print-friendly zero-state — replaces a bare empty table header whenever a report
 *  section genuinely has no data for the current snapshot (e.g. zero lead inquiries), rather
 *  than rendering column headers over an empty body. */
export function ReportEmptyState({ message }: { message: string }) {
  return (
    <p className="rounded-md border border-dashed border-zim-border py-3 text-center text-xs text-zim-muted">
      {message}
    </p>
  );
}

/** A simple two/three-column data table used across report sections. Renders a `ReportEmptyState`
 *  instead of a bare empty header whenever `rows` is empty, so every section degrades gracefully
 *  with no data rather than looking broken. */
export function ReportTable({
  columns,
  rows,
  emptyMessage,
}: {
  columns: string[];
  rows: (string | number)[][];
  emptyMessage?: string;
}) {
  if (rows.length === 0) {
    return <ReportEmptyState message={emptyMessage ?? "No records for this snapshot."} />;
  }
  return (
    <table className="w-full border-collapse text-sm">
      <thead>
        <tr className="border-b border-zim-border text-left">
          {columns.map((c) => (
            <th key={c} className="py-1.5 pr-4 text-[11px] uppercase tracking-wide text-zim-muted">
              {c}
            </th>
          ))}
        </tr>
      </thead>
      <tbody>
        {rows.map((row, i) => (
          <tr key={i} className="border-b border-zim-border/60">
            {row.map((cell, j) => (
              <td key={j} className="py-1.5 pr-4 text-zim-charcoal">
                {cell}
              </td>
            ))}
          </tr>
        ))}
      </tbody>
    </table>
  );
}

/** Wraps a data table that duplicates a chart directly above it. On screen, the table starts
 *  collapsed behind a "Show underlying data table" toggle — an executive reading on a monitor
 *  gets one clean chart with hover tooltips instead of a chart immediately followed by the exact
 *  same numbers in a table. In print/PDF (`window.print()`), the table always renders regardless
 *  of the toggle state, since a printed page has no hover interaction and auditors need the exact
 *  figures — `hidden print:block` is the standard Tailwind screen-vs-print visibility split. */
export function ReportDataToggle({ children }: { children: React.ReactNode }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="mt-3">
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        className="print:hidden text-xs font-medium text-zim-green-700 underline-offset-2 hover:underline"
      >
        {open ? "Hide underlying data table" : "Show underlying data table"}
      </button>
      <div className={open ? "mt-2 block" : "mt-2 hidden print:block"}>{children}</div>
    </div>
  );
}

/** Fixed-pixel-height chart wrapper — deliberately not purely `ResponsiveContainer`-percentage-
 *  sized, since that relies on a ResizeObserver that can report a zero width when the browser
 *  lays out the print/PDF media at generation time. Mirrors the already-working chart-sizing
 *  pattern in components/deal-room/deal-room-overview.tsx. */
export function ReportChartFrame({ height = 220, children }: { height?: number; children: React.ReactNode }) {
  return <div style={{ width: "100%", height }}>{children}</div>;
}

/** Explicit color-swatch + label legend for multi-series charts (stacked bars, pie/donut slices)
 *  whose color-to-category mapping isn't already spelled out by an axis label — e.g. a status-
 *  stacked bar or a role-breakdown pie. Renders in both screen and print (unlike ReportDataToggle,
 *  a legend is part of reading the chart itself, not a duplicate data table). */
export function ReportChartLegend({ items }: { items: { label: string; color: string }[] }) {
  if (items.length === 0) return null;
  return (
    <div className="mt-2 flex flex-wrap items-center justify-center gap-x-4 gap-y-1.5 text-[11px] text-zim-charcoal">
      {items.map((item) => (
        <span key={item.label} className="inline-flex items-center gap-1.5">
          <span className="inline-block h-2.5 w-2.5 shrink-0 rounded-full" style={{ backgroundColor: item.color }} />
          {item.label}
        </span>
      ))}
    </div>
  );
}

export function ReportSection({
  title,
  children,
  breakBefore = false,
}: {
  title: string;
  children: React.ReactNode;
  /** Forces this section to start on a new printed/PDF page — used sparingly, only at the
   *  Command Strip -> Analytics Grid boundary and before the closing Methodology appendix, so
   *  window.print() output breaks at logical section boundaries rather than mid-chart. */
  breakBefore?: boolean;
}) {
  return (
    <section className={`mb-6 break-inside-avoid ${breakBefore ? "print:break-before-page" : ""}`}>
      <h3 className="mb-2 text-sm font-semibold uppercase tracking-wide text-zim-green-700">{title}</h3>
      {children}
    </section>
  );
}
