import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join } from "node:path";

let commit = "unknown";
try {
  commit = execSync("git rev-parse --short HEAD", { encoding: "utf8" }).trim();
} catch {
  // Deploy host may not have git available.
}

const builtAt = new Date().toISOString();
const outPath = join(process.cwd(), "lib", "config", "build-info.ts");

const contents = `// GENERATED by scripts/write-build-info.ts — do not edit by hand.
export const BUILD_INFO = {
  commit: ${JSON.stringify(commit)},
  builtAt: ${JSON.stringify(builtAt)},
} as const;
`;

writeFileSync(outPath, contents, "utf8");
console.log(`Wrote ${outPath} (commit=${commit}, builtAt=${builtAt})`);
